bug44: ax_fortify.m4 reproduce
The bug states:
io-utils.cc:1002:10: error: writing 1 byte into a
region of size 0 [-Werror=stringop-overflow=]

This commit doesn't fix the bug, but reproduces it if you:
./configure --with-fortify

The problem appears to be that compiling with
	g++ ... -O -D_FORTIFY_SOURCE=2 ...
there are no errors, but there is one if you compile with
        g++ ... -O2 -D_FORTIFY_SOURCE=2 ...
The optimisation causes the problem to manifest.